# Generated by Django 5.2.4 on 2025-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_alter_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeck',
            name='max_cards',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userdeck',
            name='min_cards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
