# Generated by Django 5.2.4 on 2025-08-28 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_alter_userdeck_max_cards_alter_userdeck_min_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdeck',
            unique_together={('user', 'deck')},
        ),
    ]
